### ISSUE TITLE
What's the difference to chai-jest-snapshot?

### ISSUE THREAD

**Issue by fatso83** [wellguimaraes/mocha-snapshots#11]
I started using [chai-jest-snapshot](https://github.com/suchipi/chai-jest-snapshot) some time before this project was started. As the API is almost 1:1, I wondered what the motivation for this library was? Are there key differences one should be aware of, for instance features that are only present in this?

**Comment by wellguimaraes** [comment]
I wasn't aware of chai-jest-snapshot when this one was created :(
