### ISSUE TITLE
Question: add support for cli parameter -u to update snapshots instead of env_var?

### ISSUE THREAD

**Issue by sdwvit** [wellguimaraes/mocha-snapshots#2]
First of all, thank you for this library!

My question is described in heading. 
I understand that for this, you may want to wrap test execution to handle cli params, but that would be a good alternative for conflicting env_var (UPDATE is too plain and might be used for other purposes)

**Comment by wellguimaraes** [comment]
Sorry for the delay. It's possible now with the `--update` flag
