### ISSUE TITLE
Why is clearing classnames necessary?

### ISSUE THREAD

**Issue by markerikson** [wellguimaraes/mocha-snapshots#4]
I'm playing around with snapshot testing for the first time, and I'm trying out this library.  I was _very_ surprised to see that it's altering the provided classnames in a component.  Why is this necessary?

As an example, a classname of `"abc-test-1 abc-test-2"` gets turned into `"abc abc"`, which seems very wrong and confusing.

It looks like I can kinda work around this by manually calling the `toJson()` method myself, like `expect(toJson($wrapper)).to.matchSnapshot()`, but I don't understand why it's trying to alter the classnames in the first place.

**Comment by wellguimaraes** [comment]
You're right, it should be optional.

When I first wrote the lib, I did that to prevent false mismatches while using css libs that generates classNames with random suffixes. 

I made it optional on v4.1.0. Check here: https://github.com/wellguimaraes/mocha-snapshots#disable-classnames-cleanup

To keep compatibility with previous versions, I kept it on by default. But you just need to turn it off once, before running tests.

Thanks for pointing that ;)
