### ISSUE TITLE
error for typescript

### ISSUE THREAD

**Issue by ddoronin** [wellguimaraes/mocha-snapshots#5]
Hey! This library looks awesome! I hate jest because it's slow as 🐌 hell .

But when I run mocha:
`./node_modules/.bin/mocha --require ts-node/register --require mocha-snapshots ./test/**/*.spec.ts*
`
got this error 🐞:

> return new TSError(diagnosticText, diagnosticCodes)
>            ^
> TSError: ⨯ Unable to compile TypeScript:
> test/Match.spec.tsx(18,28): error TS2339: Property 'matchSnapshot' does not exist on type 'Assertion'.

https://github.com/ddoronin/reoption
yarn install
yarn test

**Comment by wellguimaraes** [comment]
@ddoronin You can add this to your `globals.d.ts` file (if you don't have it, create it on the root folder of the project):

```
declare namespace Chai {
  export interface Assertion {
    matchSnapshot(): void;
  }
}
```
